### ISSUE TITLE
wrapper

### ISSUE THREAD

**Issue by under-score** [jankais3r/pyPhotoDNA#2]
includes a huge library that I don't need ... Isn't there [any PhotoDNA alike](https://www.hackerfactor.com/blog/index.php?/archives/931-PhotoDNA-and-Limitations.html) Python implementation out there?

**Comment by jankais3r** [comment]
Depends on your definition of huge… The library itself has few tens of kilobytes and contains very few things on top of the robust hashing algorithm…

To answer your question directly, I am not aware of any open source implementation of the algorithm, but it should be possible to write one using information in the article that you linked.
