### ISSUE TITLE
Not Able to Download AXIOM

### ISSUE THREAD

**Issue by celcof** [jankais3r/pyPhotoDNA#7]
Trying to run the install.sh from an Ubuntu system I am not able to download the 4.4 GB Axiom Tool: I guess it not anymore freely available?

**Comment by Euro-pol** [comment]
i think they removed it, because if you go on the direct link u get

```<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
</Error>
```

**Comment by jankais3r** [comment]
Hi, I just pushed a commit with a new download link. Please try.
